ChannelOne/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.login_reg.urls', namespace='login_reg')),
    path('chat/', include('apps.chat.urls', namespace='chat')),
]

apps/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('room/<str:room_name>', views.index, name='index'),
    path('create/', views.create_room, name='create_room'),
]

apps/login_reg/urls.py
from django.urls import path
from . import views

app_name = 'login_reg'

urlpatterns = [
    path('', views.index, name='index'),
    path('bills', views.bills, name='bills'),
    path('get_bills', views.get_bills, name='get_bills'),
    path('save_bill', views.save_bill, name='save_bill'),
    path('delete_bill/<int:bill_id>', views.delete_bill, name='delete_bill'),
    path('update_bill/<int:bill_id>', views.update_bill, name='update_bill'),
    path('projects', views.projects, name='projects'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('authenticate/<str:auth_for>', views.authenticate, name='authenticate'),
    path('logout', views.logout, name='logout'),
    path('authenticate_ajax/<str:auth_for>', views.authenticate_ajax, name='authenticate_ajax'),
    path('demo', views.demo, name='demo'),
]

apps/chat/models.py
from django.db import models

# Create your models here.

apps/login_reg/models.py
from django.db import models

class User(models.Model):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=64)
    password = models.CharField(max_length=256)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def join_dt(self):
        return datetime.strftime(self.created_at, '%B %d, %Y')

class BillItem(models.Model):
    description = models.CharField(max_length=64)
    amount = models.FloatField()

    user = models.ForeignKey(User, related_name='bills', on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/chat/views.py
from django.shortcuts import render, redirect

def index(request, room_name):
    context = {
        'room_name': room_name
    }
    return render(request, 'chat/index.html', context)

def create_room(request):
    if request.method == 'POST':
        return redirect('chat:index', room_name=request.POST['room_name'].replace(' ', '-'))

    return redirect('login_reg:index')

apps/login_reg/views.py
import bcrypt, json
from time import sleep

from django.http import JsonResponse
from django.shortcuts import render, redirect, reverse
from django.contrib import messages

from apps.login_reg.models import User, BillItem

def demo(request):
    return render(request, 'login_reg/demo.html')

def bills(request):
    if 'user_id' in request.session:
        return render(request, 'login_reg/bills.html')
    return redirect('login_reg:index')

def save_bill(request):
    if request.method == 'POST':
        try:
            description = request.POST['html_description']
            amount = float(request.POST['html_amount'])
            bill = BillItem.objects.create(user_id=request.session['user_id'], description=description, amount=amount)
            delete_url = reverse('login_reg:delete_bill', kwargs={'bill_id': bill.id})
            update_url = reverse('login_reg:update_bill', kwargs={'bill_id': bill.id})
            return JsonResponse({
                'description': description, 
                'amount': amount, 
                'bill_id': bill.id, 
                'delete_url': delete_url, 
                'update_url': update_url
            })
        except:
            raise
            return JsonResponse({'error': 'Server error'}, status=500)

    return JsonResponse({'error': 'Method Not Allowed'}, status=405)

def get_bills(request):
    bills = []
    for bill in BillItem.objects.filter(user_id=request.session['user_id']):
        delete_url = reverse('login_reg:delete_bill', kwargs={'bill_id': bill.id})
        update_url = reverse('login_reg:update_bill', kwargs={'bill_id': bill.id})
        bill_dictionary = {
                'description': bill.description, 
                'amount': bill.amount, 
                'bill_id': bill.id, 
                'delete_url': delete_url, 
                'update_url': update_url
            }
        bills.append(bill_dictionary)
    return JsonResponse(json.dumps(bills), safe=False)

def update_bill(request, bill_id):
    bill = BillItem.objects.get(id=bill_id)
    bill.description = request.POST['description']
    bill.amount = request.POST['amount']
    bill.save()
    return JsonResponse({'OK': 'it worked!'})


def delete_bill(request, bill_id):
    try:
        BillItem.objects.get(id=bill_id).delete()
        return JsonResponse({'message': 'Bill deleted'})
    except:
        pass

    return JsonResponse({'error': 'Server error'}, status=500)

def projects(request):
    return render(request, 'login_reg/projects.html')

def index(request):
    return render(request, 'login_reg/index.html')

def logout(request):
    request.session.clear()
    return redirect('login_reg:index')

def login(request):
    return render(request, 'login_reg/login.html')

def register(request):
    return render(request, 'login_reg/register.html')

def authenticate_ajax(request, auth_for):
    if request.method == 'POST':
        success = False
        user = None

        if auth_for == 'login':
            success, user = login_user(request)
        elif auth_for == 'register':
            success, user = register_user(request)

        if success:
            start_session(request, user)
            return JsonResponse({'url': redirect('login_reg:index').url})
        
        errors = []

        for message in messages.get_messages(request):
            errors.append(str(message))

        return JsonResponse({'errors': errors})

    return redirect('login_reg:index')

def authenticate(request, auth_for):
    if request.method == 'POST':
        success = False
        user = None

        if auth_for == 'login':
            success, user = login_user(request)
        elif auth_for == 'register':
            success, user = register_user(request)

        if success:
            start_session(request, user)
            return redirect('login_reg:index')
        else:
            return redirect('login_reg:'+auth_for)

    return redirect('login_reg:index')


def login_user(request):
    email = request.POST['html_email']
    password = request.POST['html_password']
    is_valid = check_length(request, email, 'Email')
    is_valid = check_length(request, password, 'Password')

    if is_valid:
        try:
            user = User.objects.get(email=email)
            if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
                return True, user
            else:
                messages.error(request, 'Invalid email or password')
        except:
            messages.error(request, 'Email not found. Please register.')

    return False, None



def register_user(request):
    username = request.POST['html_username']
    email = request.POST['html_email']
    password = request.POST['html_password']
    confirm = request.POST['html_confirm']

    is_valid = check_length(request, username, 'Full name')
    is_valid = check_length(request, email, 'Email')
    is_valid = check_length(request, password, 'Password')
    is_valid = check_length(request, confirm, 'Confirm password')

    if password != confirm:
        messages.error(request, 'Passwords do not match')
        is_valid = False

    if is_valid:
        try:
            user = User.objects.create(username=username, email=email, password=bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8'))
            return True, user
        except:
            raise
            messages.error(request, 'That email address is already in use.  Please use a different email address.')

    
    return False, None


def start_session(request, user):
    request.session['user_id'] = user.id
    request.session['username'] = user.username


def check_length(request, data, name):
    if len(data) == 0:
        messages.error(request, name + ' cannot be left blank')
        return False

    return True

apps/chat/templates/chat/index.html
{% extends 'login_reg/base.html' %} {% block body %}

<div class="container">
    <div class="text-center">{{room_name}}</div>
    <div class="row">
        <div class="col-12">
            <div class="row">
                <div class="content-pane">
                    <div id="messages-list"></div>
                </div>
            </div>
            <div class="col-12 p-0 mt-4">
                <form action="">
                    <input type="text" class="form-control" id="send-message">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %} {% block scripts %}

<script>
    $(document).ready(function () {
        let connection = new WebSocket("ws://localhost:8000/ws/chat/{{room_name}}")

        $("#send-message").keypress(function(event) {
            if (event.keyCode === 13) {
                event.preventDefault()
                let message = {
                    "message": $(this).val(),
                };
                connection.send(JSON.stringify(message));
                $(this).val(null);
            }
        });

        connection.onmessage = function(response) {
            let data = JSON.parse(response.data);
            if (data.success) {
                if (data.notification) {
                    let messageDiv = $("<div></div");
                    messageDiv.addClass("notification");
                    messageDiv.text(data.notification);
                    $("#messages-list").append(messageDiv);

                } else if (data.message) {
                    let userSpan = createElement("span", data.username + ": ", ["username"]);
                    let messageSpan = createElement("span", data.message, ["username"]);
                    let messageDiv = createElement("div", null, ["message"]);
                    messageDiv.append(userSpan).append(messageSpan);
                    messageDiv.appendTo("#messages-list");
                }

                $(".content-pane").animate({
                    scrollTop: $(".content-pane").prop("scrollHeight")
                    
                }, 2000)
            }
        }


    });


</script> {% endblock %}

apps/login_reg/templates/login_reg/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title>ChannelOne</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'login_reg/lib/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'login_reg/lib/font-awesome.min.css' %}">

  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'login_reg/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'login_reg/css/default.css' %}">


</head>

<body>
    {% include 'login_reg/navbar.html' %}
    {% block body %} {% endblock %}


    <script src="{% static 'login_reg/lib/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'login_reg/lib/popper.min.js' %}"></script>
    <script src="{% static 'login_reg/lib/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>

    <script src="{% static 'login_reg/js/utilities.js' %}"></script>

    {% block scripts %} {% endblock %}
</body>

</html>

apps/login_reg/templates/login_reg/index.html
{% extends 'login_reg/base.html' %} {% block body %}

<div class="container mt-4">
    {% if request.session.user_id %}
    <h1>Start a room...</h1>
    <form action="{% url 'chat:create_room' %}" method="POST">
        <div class="form-inline">
            <input type="text" class="form-control col-10" placeholder="Room name" name="room_name"> {% csrf_token %}
            <button type="submit" class="btn btn-success ml-2">Join</button>
        </div>
    </form>
    {% else %}

    <h1>Login to chat...</h1>
    {% endif %}
</div>
{% endblock %}

apps/login_reg/templates/login_reg/login.html
{% extends 'login_reg/base.html' %} {% block body %}

<div class="card my-4 col-6 offset-3 p-5">
    <h3 class="text-center">Login</h3>
    <form method="POST" action="{% url 'login_reg:authenticate_ajax' auth_for='login' %}" id="login-form">
        <div class="form-group">
            <label for="inputEmail1">Email</label>
            <input type="email" class="form-control" id="inputEmail1" aria-describedby="emailHelp" placeholder="Enter Email" name="html_email"
                value="">
        </div>
        <div class="form-group">
            <label for="inputPassword1">Password</label>
            <input type="password" class="form-control" id="inputPassword1" placeholder="Enter Password" name="html_password" value="">
        </div>
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Login</button>
        <i class="fa fa-spinner ml-3 fa-spin" id="spinner" style="display: none"></i>
    </form>
    <div class="my-3 messages">
        
    </div>
</div>


{% endblock %} {% block scripts %}
<script>

    let beforeAjaxSend = function (xhr, settings) {
        let csrftoken = Cookies.get('csrftoken');
        if (!this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    };

    $(document).ready(function () {


        $("#login-form").submit(function (event) {
            event.preventDefault();
            $(".alert").remove();
            $("#spinner").show();

            let formFields = formToJson("#login-form");
            formFields.html_password = encryptPassword(formFields.html_password);

            $.ajax({
                type: "POST",
                url: $("#login-form").attr("action"),
                data: formFields,
                success: function (response) {
                    $("#spinner").hide();
                    if (response.errors) {
                        displayErrors(".messages", response.errors);
                    } else if (response.url) {
                        window.location = response.url;
                    }
                }
            });
        });
    });


</script> {% endblock %}

apps/login_reg/templates/login_reg/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">

    
        <a class="navbar-brand" href="{% url 'login_reg:index' %}">ChannelOne</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    {% if request.session.user_id %}
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        {{request.session.username}}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'login_reg:logout' %}">Logout</a>
                    </div>
                    {% else %}
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        Sign In
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'login_reg:login' %}">Login</a>
                        <a class="dropdown-item" href="{% url 'login_reg:register' %}">Register</a>
                        
                    </div>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

apps/login_reg/templates/login_reg/register.html
{% extends 'login_reg/base.html' %} {% block body %}

<div class="card my-4 col-6 offset-3 p-5">
    <h3 class="text-center">Register</h3>
    <form method="POST" action="{% url 'login_reg:authenticate_ajax' auth_for='register' %}" id="register-form">
        <div class="form-group">
            <label for="inputEmail1">Email Address</label>
            <input type="email" class="form-control" id="inputEmail1" aria-describedby="emailHelp" placeholder="Enter Email Address"
                name="html_email">
        </div>
        <div class="form-group">
            <label for="inputUserName1">Full Name</label>
            <input type="text" class="form-control" id="inputUserName1" aria-describedby="usernameHelp" placeholder="Enter UserName"
                name="html_username">
        </div>
        <div class="form-group">
            <label for="inputPassword1">Password</label>
            <input type="password" class="form-control" id="inputPassword1" placeholder="Create Password" name="html_password">
        </div>
        <div class="form-group">
            <label for="inputPassword2">Confirm Password</label>
            <input type="password" class="form-control" id="inputPassword2" placeholder="Confirm Password" name="html_confirm">
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
        <i class="fa fa-spinner ml-3 fa-spin" id="spinner" style="display: none"></i>
    </form>

    <div class="my-3 messages">
        
    </div>
</div>

{% endblock %} {% block scripts %}
<script>
    let beforeAjaxSend = function (xhr, settings) {
        let csrftoken = Cookies.get('csrftoken');
        if (!this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    };

    $(document).ready(function () {

        $("#register-form").submit(function (event) {
            event.preventDefault();
            $(".alert").remove();
            $("#spinner").show();

            let formFields = formToJson("#register-form");

            formFields.html_password = encryptPassword(formFields.html_password);
            formFields.html_confirm = encryptPassword(formFields.html_confirm);

            $.ajax({
                beforeSend: beforeAjaxSend,
                type: "POST",
                url: $("#register-form").attr("action"),
                data: formFields,
                success: function (response) {
                    console.log(formFields)
                    $("#spinner").hide();
                    if (response.errors) {
                        displayErrors(".messages", response.errors);
                    } else if (response.url) {
                        window.location = (response.url);
                    }
                }
            });
        });
    });
</script> {% endblock %}